### ISSUE TITLE
Single track activities

### ISSUE THREAD

**Issue by versatilehuman** [smartchicago/trailsy#116]
Single track technically allows same as unpaved (bike, hike, equestrian, x-country ski). Can we update?

https://fpcc-staging.smartchicagoapps.org/#/?trail=Palos+Trail+System

**Comment by shua123** [comment]
Fixed on gh-pages version

**Comment by versatilehuman** [comment]
Still seeing hiking only on gh-pages:

![image](https://cloud.githubusercontent.com/assets/7032169/19198911/1a36cf48-8c87-11e6-944e-2d691ca4a96f.png)

**Comment by shua123** [comment]
fixed
