### ISSUE TITLE
Clicking on a result from homepage leads to a partially loaded page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/trailsy#26]
Whenever I click on one of the (entrance?) results from the homepage, I am lead to a partially loaded page in about same location. The top few results on my homepage I tried are listed from my "Current Location" at 225 N. Michigan.

Here is when I click on Irene C. Hernandez Family Picnic Area from the homepage:
<img width="1223" alt="screen shot 2016-02-15 at 12 10 31 pm" src="https://cloud.githubusercontent.com/assets/5550969/13056874/f19c2bd0-d3dd-11e5-8b93-5c40dbb679bb.png">

LaBagh Woods:
<img width="1220" alt="screen shot 2016-02-15 at 12 09 33 pm" src="https://cloud.githubusercontent.com/assets/5550969/13056879/fd605540-d3dd-11e5-8037-70769be194fc.png">

Forest Glen Woods:
<img width="1224" alt="screen shot 2016-02-15 at 12 10 48 pm" src="https://cloud.githubusercontent.com/assets/5550969/13056885/061b6d14-d3de-11e5-8447-64827b7bc3a1.png">

Whenever I exit out of that location result and click another result I go to a correct, properly loaded page. See here:
<img width="1221" alt="screen shot 2016-02-15 at 12 20 34 pm" src="https://cloud.githubusercontent.com/assets/5550969/13056951/8b1d59dc-d3de-11e5-81de-5716e118746e.png">

**Comment by shua123** [comment]
This is really weird. What browser? Windows or mac? @smarziano

**Comment by smarziano** [comment]
I have done a few tests. This same error happens both on Windows and Mac on these browsers: Chrome, Internet Explorer, and Firefox.

**Comment by shua123** [comment]
Centering is not working right at first but then does

**Comment by shua123** [comment]
Fixed with commit https://github.com/smartchicago/trailsy/commit/7921ad7f296b6fd3205ccc1060cc69e755ed4e93

**Comment by smarziano** [comment]
@shua123 This is still an issue for locations that are further away. Here is an example of clicking on "Tower Road" with current location set at 225 N. Michigan Ave:

<img width="1256" alt="screen shot 2016-02-16 at 9 53 21 am" src="https://cloud.githubusercontent.com/assets/5550969/13081655/426ba5a8-d493-11e5-8566-0804f0bdde03.png">

Here is another example where the map will not load but the trails do for "Cap Sauers Holdings Nature Preserve:
<img width="1257" alt="screen shot 2016-02-16 at 9 55 20 am" src="https://cloud.githubusercontent.com/assets/5550969/13081714/7ce09c02-d493-11e5-9219-e9fd54afa87d.png">

**Comment by shua123** [comment]
The issue appears with the first movement after load. Part of the transform pan does not reset correctly. There seems to be a variety of fixes integrated into Leaflet over time but nothing that solves the issue completely. https://www.google.com/?gws_rd=ssl#q=leaflet+tilelayer+map+freeze 
Disabling 3D appears to "solve" the issue by avoiding it. The downside is that we lose the pan/zoom animation. Ideally we find a better solution later.

@smarziano Can you please check if it works better now for you?

**Comment by smarziano** [comment]
@shua123 This is working much better now. I've tried multiple results (especially some of the further distance results) and all of them are loading properly. I did not notice a difference or that we lost the pan/zoom animation.

**Comment by shua123** [comment]
:trophy:
